package formview;

import formview.menu;
import formview.BankATM;
import java.util.LinkedList;
import java.util.Queue;
import javax.swing.JOptionPane;

public class antrian extends javax.swing.JFrame {
    int jml;
    Queue bolang = new LinkedList(); 
    public antrian() {
        initComponents();
        this.setLocationRelativeTo(null);
        bt_move.setEnabled(false);
//      bt_move1.setVisible(false);
        this.getContentPane().setBackground(new java.awt.Color(11,189,189));
    }
     
    void input(int jml) {
        int i = 0;
        for(int j=0; j<jml; j++){
            i =j;
            bolang.add(i); 
        }
        jJml.setText(Integer.toString(jml));
        bt_input.setEnabled(false);
    }

    
    // 
    void move(){
        int hasil = 0;
        if(bolang.peek()==null){
            JOptionPane.showMessageDialog(rootPane, "Queue kosong");
//            ta1.setText("");
            bt_input.setEnabled(true);
            bt_move.setEnabled(false);
//            bt_move1.setEnabled(false);
       }else{
//            ta2.append(bolang.peek() + "\n");
            bolang.poll();
//            ta1.setText(bolang + "");
            
            
            int number = Integer.parseInt(jJml.getText());
            int kurang = 1;
            hasil = number - kurang;
        }
        jJml.setText(Integer.toString(hasil));
        if(hasil == 0) {
            bt_input.setEnabled(true);
            bt_move.setEnabled(false);
        }
        
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bt_input = new javax.swing.JButton();
        bt_move = new javax.swing.JButton();
        bt_exit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jJml = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bt_input.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bt_input.setText("Tambah Antrian");
        bt_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_inputActionPerformed(evt);
            }
        });
        getContentPane().add(bt_input, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, -1, -1));

        bt_move.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bt_move.setText("Layani");
        bt_move.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_moveActionPerformed(evt);
            }
        });
        getContentPane().add(bt_move, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, 130, -1));

        bt_exit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bt_exit.setText("Exit");
        bt_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_exitActionPerformed(evt);
            }
        });
        getContentPane().add(bt_exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, 130, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("ANTRIAN BANK");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 130, -1));

        jJml.setFont(new java.awt.Font("Tahoma", 0, 60)); // NOI18N
        jJml.setText("0");
        getContentPane().add(jJml, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, -1, -1));

        jLabel2.setText("Menu Antrian");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, -1, -1));

        jLabel5.setFont(new java.awt.Font("SF Pro Text", 0, 12)); // NOI18N
        jLabel5.setText("PT. BANK BITCOIN");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, 240, 60));

        jLabel3.setText("Jumlah Antrian");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, -1, 20));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/bitcoin-text.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, -1, 70));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 170, 140));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 70));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // ketika tombol tambah antrian di klik dan memasukan angka , maka method action ini akan dijalankan
    private void bt_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_inputActionPerformed
        // TODO add your handling code here:
        
        // inputan jumlah angka dimasukan kesini
        jml = Integer.parseInt(JOptionPane.showInputDialog("Masukan angka : "));
        
        // jika di masukan angka dibawah 0
        if(jml < 0){
            JOptionPane.showMessageDialog(rootPane, "Angka yang anda masukan salah.");
        }else{
            input(jml);
    //        ta2.setText("");
            bt_move.setEnabled(true);
    //        bt_move1.setVisible(true);
    //        bt_move1.setEnabled(false);
        }
    }//GEN-LAST:event_bt_inputActionPerformed

    private void bt_moveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_moveActionPerformed
        move();
//        this.hide();

        // berpindah ke class BankATM
        new BankATM().show();
        
        
//        bt_move.setEnabled(false);
//        bt_move1.setEnabled(true);
    }//GEN-LAST:event_bt_moveActionPerformed

    private void bt_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_exitActionPerformed
        // TODO add your handling code here: 
        
        // jika tombol exit di klik maka, langsung memanggil class menu().
        new menu().show();
    }//GEN-LAST:event_bt_exitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(antrian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(antrian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(antrian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(antrian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new antrian().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_exit;
    private javax.swing.JButton bt_input;
    private javax.swing.JButton bt_move;
    private javax.swing.JLabel jJml;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables

}
